services:
  - type: web
    name: virtual-telegram
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install && pnpm build
    startCommand: pnpm serve
    envVars:
      - fromGroup: virtual-telegram
      - key: DATABASE_URL
        fromDatabase:
          name: virtual-telegram
          property: connectionString
    domains:
      - "api.virtual-telegram.com"
databases:
  - name: virtual-telegram
    databaseName: virtual-telegram
    user: admin
    plan: starter
