// const countries = [
//   { flag: "🇦🇱", name: "Albania", code: "AL" },
//   { flag: "🇦🇷", name: "Argentina", code: "AR" },
//   { flag: "🇦🇺", name: "Australia", code: "AU" },
//   { flag: "🇦🇹", name: "Austria", code: "AT" },
//   { flag: "🇧🇩", name: "Bangladesh ", code: "BD" },
//   { flag: "🇧🇦", name: "Bos. and Herz. ", code: "BA" },
//   { flag: "🇧🇷", name: "Brazil", code: "BR" },
//   { flag: "🇧🇬", name: "Bulgaria", code: "BG" },
//   { flag: "🇰🇭", name: "Cambodia", code: "KH" },
//   { flag: "🇨🇦", name: "Canada ", code: "CA" },
//   { flag: "🇨🇱", name: "Chile ", code: "CL" },
//   { flag: "🇨🇴", name: "Colombia", code: "CO" },
//   { flag: "🇭🇷", name: "Croatia", code: "HR" },
//   { flag: "🇨🇾", name: "Cyprus", code: "CY" },
//   { flag: "🇨🇿", name: "Czech Republic", code: "CZ" },
//   { flag: "🇩🇰", name: "Denmark", code: "DK" },
//   { flag: "🇩🇴", name: "Dominicana ", code: "DO" },
//   { flag: "🇪🇬", name: "Egypt", code: "EG" },
//   { flag: "🇪🇪", name: "Estonia", code: "EE" },
//   { flag: "🇫🇮", name: "Finland", code: "FI" },
//   { flag: "🇫🇷", name: "France ", code: "FR" },
//   { flag: "🇬🇪", name: "Georgia ", code: "GE" },
//   { flag: "🇩🇪", name: "Germany", code: "DE" },
//   { flag: "🇬🇭", name: "Ghana", code: "GH" },
//   { flag: "🇬🇮", name: "Gibraltar ", code: "GI" },
//   { flag: "🇬🇷", name: "Greece ", code: "GR" },
//   { flag: "🇭🇰", name: "Hong Kong", code: "HK" },
//   { flag: "🇭🇺", name: "Hungary ", code: "HU" },
//   { flag: "🇮🇳", name: "India", code: "IN" },
//   { flag: "🇮🇩", name: "Indonesia", code: "ID" },
//   { flag: "🇮🇶", name: "Iraq", code: "IQ" },
//   { flag: "🇮🇪", name: "Ireland", code: "IE" },
//   { flag: "🇮🇱", name: "Israel", code: "IL" },
//   { flag: "🇮🇹", name: "Italy", code: "IT" },
//   { flag: "🇰🇿", name: "Kazakhstan", code: "KZ" },
//   { flag: "🇰🇪", name: "Kenya", code: "KE" },
//   { flag: "🇰🇬", name: "Kyrgyzstan (Virtual)", code: "KG" },
//   { flag: "🇱🇦", name: "Laos", code: "LA" },
//   { flag: "🇱🇻", name: "Latvia", code: "LV" },
//   { flag: "🇱🇹", name: "Lithuania", code: "LT" },
//   { flag: "🇲🇰", name: "Macedonia", code: "MK" },
//   { flag: "🇲🇾", name: "Malaysia", code: "MY" },
//   { flag: "🇲🇽", name: "Mexico", code: "MX" },
//   { flag: "🇲🇦", name: "Morocco", code: "MA" },
//   { flag: "🇳🇱", name: "Netherlands", code: "NL" },
//   { flag: "🇳🇬", name: "Nigeria", code: "NG" },
//   { flag: "🇳🇴", name: "Norway", code: "NO" },
//   { flag: "🇵🇰", name: "Pakistan", code: "PK" },
//   { flag: "🇵🇾", name: "Paraguay ", code: "PY" },
//   { flag: "🇵🇭", name: "Philippines ", code: "PH" },
//   { flag: "🇵🇱", name: "Poland", code: "PL" },
//   { flag: "🇵🇹", name: "Portugal", code: "PT" },
//   { flag: "🇷🇴", name: "Romania", code: "RO" },
//   { flag: "🇷🇺", name: "Russian Federation", code: "RU" },
//   { flag: "🇷🇸", name: "Serbia", code: "RS" },
//   { flag: "🇸🇬", name: "Singapore", code: "SG" },
//   { flag: "🇸🇰", name: "Slovakia ", code: "SK" },
//   { flag: "🇸🇮", name: "Slovenia", code: "SI" },
//   { flag: "🇿🇦", name: "South Africa", code: "ZA" },
//   { flag: "🇪🇸", name: "Spain", code: "ES" },
//   { flag: "🇸🇪", name: "Sweden", code: "SE" },
//   { flag: "🇹🇿", name: "Tanzania", code: "TZ" },
//   { flag: "🇹🇭", name: "Thailand", code: "TH" },
//   { flag: "🇹🇷", name: "Turkey", code: "TR" },
//   { flag: "🇺🇦", name: "Ukraine", code: "UA" },
//   { flag: "🇺🇸", name: "United States", code: "US" },
//   { flag: "🇬🇧", name: "Unt. Kingdom", code: "UK" },
//   { flag: "🇺🇿", name: "Uzbekistan", code: "UZ" },
//   { flag: "🇻🇳", name: "Vietnam", code: "VN" },
// ] as const;

const countries = [
  { flag: "🇦🇺", name: "Australia", code: "AU" },
  { flag: "🇦🇹", name: "Austria", code: "AT" },
  { flag: "🇧🇪", name: "Belgium", code: "BE" },
  { flag: "🇨🇦", name: "Canada", code: "CA" },
  { flag: "🇩🇰", name: "Denmark", code: "DK" },
  { flag: "🇫🇮", name: "Finland", code: "FI" },
  { flag: "🇫🇷", name: "France", code: "FR" },
  { flag: "🇩🇪", name: "Germany", code: "DE" },
  { flag: "🇭🇰", name: "Hong Kong", code: "HK" },
  { flag: "🇮🇪", name: "Ireland", code: "IE" },
  { flag: "🇮🇹", name: "Italy", code: "IT" },
  { flag: "🇯🇵", name: "Japan", code: "JP" },
  { flag: "🇰🇷", name: "South Korea", code: "KR" },
  { flag: "🇱🇺", name: "Luxembourg", code: "LU" },
  { flag: "🇳🇱", name: "Netherlands", code: "NL" },
  { flag: "🇳🇿", name: "New Zealand", code: "NZ" },
  { flag: "🇳🇴", name: "Norway", code: "NO" },
  { flag: "🇸🇬", name: "Singapore", code: "SG" },
  { flag: "🇪🇸", name: "Spain", code: "ES" },
  { flag: "🇸🇪", name: "Sweden", code: "SE" },
  { flag: "🇨🇭", name: "Switzerland", code: "CH" },
  { flag: "🇬🇧", name: "United Kingdom", code: "UK" },
  { flag: "🇺🇸", name: "United States", code: "US" },
] as const;

export type Country = (typeof countries)[number];
export type CountryCode = Country["code"];
export default countries;
