const countries = [
  {
    flag: "\ud83c\uddf7\ud83c\uddfa",
    name: "Russian Federation",
    code: "RU",
  },
  { flag: "\ud83c\udde8\ud83c\udde6", name: "Canada ", code: "CA" },
  { flag: "\ud83c\uddfa\ud83c\uddf8", name: "United States", code: "US" },
  { flag: "\ud83c\uddfa\ud83c\uddf0", name: "Unt. Kingdom", code: "UK" },
  { flag: "\ud83c\uddeb\ud83c\uddf7", name: "France ", code: "FR" },
  { flag: "\ud83c\udde9\ud83c\uddea", name: "Germany", code: "DE" },
  { flag: "\ud83c\uddee\ud83c\uddf9", name: "Italy", code: "IT" },
  { flag: "\ud83c\uddea\ud83c\uddf8", name: "Spain", code: "ES" },
  { flag: "\ud83c\udde6\ud83c\uddf1", name: "Albania", code: "AL" },
  { flag: "\ud83c\udde6\ud83c\uddf7", name: "Argentina", code: "AR" },
  { flag: "\ud83c\udde6\ud83c\uddfa", name: "Australia", code: "AU" },
  { flag: "\ud83c\udde6\ud83c\uddf9", name: "Austria", code: "AT" },
  { flag: "\ud83c\udde7\ud83c\udde9", name: "Bangladesh ", code: "BD" },
  {
    flag: "\ud83c\udde7\ud83c\udde6",
    name: "Bos. and Herz. ",
    code: "BA",
  },
  { flag: "\ud83c\udde7\ud83c\uddf7", name: "Brazil", code: "BR" },
  { flag: "\ud83c\udde7\ud83c\uddec", name: "Bulgaria", code: "BG" },
  { flag: "\ud83c\uddf0\ud83c\udded", name: "Cambodia", code: "KH" },
  { flag: "\ud83c\udde8\ud83c\uddf1", name: "Chile ", code: "CL" },
  { flag: "\ud83c\udde8\ud83c\uddf4", name: "Colombia", code: "CO" },
  { flag: "\ud83c\udded\ud83c\uddf7", name: "Croatia", code: "HR" },
  { flag: "\ud83c\udde8\ud83c\uddfe", name: "Cyprus", code: "CY" },
  {
    flag: "\ud83c\udde8\ud83c\uddff",
    name: "Czech Republic",
    code: "CZ",
  },
  { flag: "\ud83c\udde9\ud83c\uddf0", name: "Denmark", code: "DK" },
  { flag: "\ud83c\udde9\ud83c\uddf4", name: "Dominicana ", code: "DO" },
  { flag: "\ud83c\uddea\ud83c\uddec", name: "Egypt", code: "EG" },
  { flag: "\ud83c\uddea\ud83c\uddea", name: "Estonia", code: "EE" },
  { flag: "\ud83c\uddeb\ud83c\uddee", name: "Finland", code: "FI" },
  { flag: "\ud83c\uddec\ud83c\uddea", name: "Georgia ", code: "GE" },
  {
    flag: "\ud83c\uddec\ud83c\udded",
    name: "Ghana (Virtual)",
    code: "GH",
  },
  { flag: "\ud83c\uddec\ud83c\uddee", name: "Gibraltar ", code: "GI" },
  { flag: "\ud83c\uddec\ud83c\uddf7", name: "Greece ", code: "GR" },
  { flag: "\ud83c\udded\ud83c\uddf0", name: "Hong Kong", code: "HK" },
  { flag: "\ud83c\udded\ud83c\uddfa", name: "Hungary ", code: "HU" },
  { flag: "\ud83c\uddee\ud83c\uddf3", name: "India", code: "IN" },
  {
    flag: "\ud83c\uddf0\ud83c\uddec",
    name: "Kyrgyzstan (Virtual)",
    code: "KG",
  },
  { flag: "\ud83c\uddf3\ud83c\uddf4", name: "Norway", code: "NO" },
  {
    flag: "\ud83c\uddf5\ud83c\uddf0",
    name: "Pakistan (Virtual)",
    code: "PK",
  },
  { flag: "\ud83c\uddf8\ud83c\uddec", name: "Singapore", code: "SG" },
  { flag: "\ud83c\uddf9\ud83c\uddff", name: "Tanzania", code: "TZ" },
  {
    flag: "\ud83c\uddfa\ud83c\uddff",
    name: "Uzbekistan (Virtual)",
    code: "UZ",
  },
  { flag: "\ud83c\uddee\ud83c\uddf6", name: "Iraq", code: "IQ" },
  { flag: "\ud83c\uddee\ud83c\udde9", name: "Indonesia", code: "ID" },
  { flag: "\ud83c\uddee\ud83c\uddea", name: "Ireland", code: "IE" },
  { flag: "\ud83c\uddee\ud83c\uddf1", name: "Israel", code: "IL" },
  { flag: "\ud83c\uddf0\ud83c\uddff", name: "Kazakhstan", code: "KZ" },
  { flag: "\ud83c\uddf0\ud83c\uddea", name: "Kenya", code: "KE" },
  { flag: "\ud83c\uddf1\ud83c\udde6", name: "Laos", code: "LA" },
  { flag: "\ud83c\uddf1\ud83c\uddfb", name: "Latvia", code: "LV" },
  { flag: "\ud83c\uddf1\ud83c\uddf9", name: "Lithuania", code: "LT" },
  { flag: "\ud83c\uddf2\ud83c\uddf0", name: "Macedonia", code: "MK" },
  { flag: "\ud83c\uddf2\ud83c\uddfe", name: "Malaysia", code: "MY" },
  { flag: "\ud83c\uddf2\ud83c\uddfd", name: "Mexico", code: "MX" },
  { flag: "\ud83c\uddf2\ud83c\udde6", name: "Morocco", code: "MA" },
  { flag: "\ud83c\uddf3\ud83c\uddf1", name: "Netherlands", code: "NL" },
  { flag: "\ud83c\uddf3\ud83c\uddec", name: "Nigeria", code: "NG" },
  { flag: "\ud83c\uddf5\ud83c\uddfe", name: "Paraguay ", code: "PY" },
  { flag: "\ud83c\uddf5\ud83c\udded", name: "Philippines ", code: "PH" },
  { flag: "\ud83c\uddf5\ud83c\uddf1", name: "Poland", code: "PL" },
  { flag: "\ud83c\uddf5\ud83c\uddf9", name: "Portugal", code: "PT" },
  { flag: "\ud83c\uddf7\ud83c\uddf4", name: "Romania", code: "RO" },
  { flag: "\ud83c\uddf7\ud83c\uddf8", name: "Serbia", code: "RS" },
  { flag: "\ud83c\uddf8\ud83c\uddf0", name: "Slovakia ", code: "SK" },
  { flag: "\ud83c\uddf8\ud83c\uddee", name: "Slovenia", code: "SI" },
  { flag: "\ud83c\uddff\ud83c\udde6", name: "South Africa", code: "ZA" },
  { flag: "\ud83c\uddf8\ud83c\uddea", name: "Sweden", code: "SE" },
  { flag: "\ud83c\uddf9\ud83c\udded", name: "Thailand", code: "TH" },
  { flag: "\ud83c\uddf9\ud83c\uddf7", name: "Turkey", code: "TR" },
  { flag: "\ud83c\uddfa\ud83c\udde6", name: "Ukraine", code: "UA" },
  { flag: "\ud83c\uddfb\ud83c\uddf3", name: "Vietnam", code: "VN" },
] as const;


export type Country = typeof countries[number];
export default countries;